spring:
  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp
#    static-path-pattern: /static/**
  #mybatis数据源
  datasource:
    url: jdbc:mysql://localhost:3306/furniture?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: system
    driver-class-name: com.mysql.cj.jdbc.Driver

  # springboot默认开启文件上传
  # 静态资源映射配置 F:/upload/ ====> http://127.0.0.1/upload
    
  resources: 
    staticLocations: file:d:/PIAimages/

#邮件发送
  mail:
    #邮箱服务器地址
    host: smtp.qq.com
    username: 869872053@qq.com
    password: sjopyrfmhrhbbcih
    default-ending: UTF-8
  
#自定义属性，谁发送邮件
mail:
 fromMail:
  addr: 869872053@qq.com
  
#日志配置
logging:
 level:
  com:
   house:
    furniture:
     dao: debug
     action: warn
     web: warn




