spring:
 mvc:
  view:
   prefix: WEB-INF/jsp/
   suffix: .jsp
   #mybatis数据源
 datasource:
  url: jdbc:mysql://127.0.0.1/furniture
  username: root
  password: a
  driver-class-name: com.mysql.jdbc.Driver
#邮件发送
 mail:
 #邮箱服务器地址
  host: smtp.qq.com
  username: 869872053@qq.com
  password: sjopyrfmhrhbbcih
  default-ending: UTF-8
  #自定义属性，谁发送邮件
mail:
 fromMail:
  addr: 869872053@qq.com
 #日志配置
logging:
 level:
  com:
   yc:
    blog:
     dao: debug
     action: warn



